//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID_Contact { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Messagee { get; set; }
        public int Flag { get; set; }
        public string Reply { get; set; }
        public int Status { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.DateTime Updated_at { get; set; }
        public int Updated_by { get; set; }
    }
}
