//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID_Post { get; set; }
        public string Post_Name { get; set; }
        public string Post_Summary { get; set; }
        public string Content { get; set; }
        public string Post_image { get; set; }
        public Nullable<System.DateTime> Date_post { get; set; }
        public Nullable<int> ID_CategoryP { get; set; }
    
        public virtual CategoryPost CategoryPost { get; set; }
    }
}
