//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Def
    {
        public int ID_Role { get; set; }
        public string Role_Name { get; set; }
        public Nullable<int> ID_RoleGroup { get; set; }
    
        public virtual role_group role_group { get; set; }
    }
}
